<Project Sdk="Microsoft.NET.Sdk.Razor">

    <ItemGroup>
      <ProjectReference Include="..\Atmos.Common\Atmos.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
      <PackageReference Include="Microsoft.Extensions.Localization" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Resources\Images\logo.svg" />
    </ItemGroup>

    <Target Name="EmbedScopedCss" BeforeTargets="AssignTargetPaths" DependsOnTargets="BundleScopedCssFiles">
      <ItemGroup>
        <EmbeddedResource Include="$(IntermediateOutputPath)scopedcss/bundle/Atmos.Templates.styles.css" LogicalName="Atmos.Templates.styles.css" />
      </ItemGroup>
    </Target>

</Project>
